### PR TITLE
Add @method for magic call

### PR DESCRIPTION
**Pull request by koriym**
add [@method](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/method.html) for `Router` class.

It helps for user input as well as clarification.

### CODE REVIEW

**Comment by harikt** [comment]
Thank you @koriym .

I have a feeling the RouteCollection could have been extended with Router than being a proxy. I did asked the same for v3. Not sure about the benefit of making the class as a proxy.

**Comment by koriym** [comment]
@harikt How do we have an another `RouterCollection` with extend ?

**Comment by harikt** [comment]
@koriym may be I am missing something.

``` php
class Router
{
    public function __construct(RouteCollection $routes, Generator $generator)
    {
        $this->routes = $routes;
        $this->generator = $generator;
    }
}
```

What I mean is 

``` php
class Router extends RouteCollection
{
    public function __construct(Generator $generator)
    {
        $this->generator = $generator;
    }
}
```

I am not seeing `addRouteCollection` , there is only set method. And if there is a call to router object method which is not defined it is handled via `__call` and via `RouteCollection` . If it is extended we don't need the method itself.

Did I missed something to understand?

Thank you.

**Comment by koriym** [comment]
@harikt Thank you for the clarify. Yes, Router has `setRoutes`. It is exchangeable.

But the relation of `Router` and `Routes`  is `is_a` ?  No. It is `has_a` relation. Router has routes.

**Comment by harikt** [comment]
Router has routes. But I am not sure whether relation ship have something to do though. As I said I may be completely wrong understanding things.

**Pull request merged**
