### PR TITLE
View helper

### PR DESCRIPTION
**Pull request by harikt**
Fixes https://github.com/auraphp/Aura.Router/issues/114

This is an updated PR of https://github.com/auraphp/Aura.Router/pull/129 which is trying to address some of the points raised on the zend-expressive url view helper which is reported https://github.com/auraphp/Aura.Router/issues/130 .

Let me know what you guys think about the same ?

### CODE REVIEW

**Comment by pine3ree** [comment]
Hello @harikt,
I haven't looked in the aura repo for a while, but it took a look at your pr and surroundings (router v.3).
so I apologize in advance if I will say something obviously wrong.

The code looks fine to me with a couple of notes:
1. I would drop support for string query params. some could add `'abc=123&def=345'`, others could add `'abc=123&amp;def=345'`, I think it's safer if the helper has the responsibility of escaping/or not the parameter separator. The same reasoning could be applied to urlencode query params values. If you have a query string you would need to use parse_url, normalize (escape/unescape and/or encode/unencode) and regenerate a query string in line with your actual requirements.
2. I've looked at the code examples, but I don't understand the $data value be assigned a string while the signature expects an array

``` php
echo $urlHelper('blog.read', 'with space', [], '', true); // helper example
//...
public function __invoke($name, array $data = [], $queryData = [], $fragment = '', $returnRawUrl = false); // helper sig
```

I've also peeked at the generator code and it seems to be that the `$data` parameter in various generate/build methods is expected to be an array (as in your __invoke) since it's being array_merged even if the signature does not require it.
If so, could all those signature be changed to `array $data = []` (or even $array $data = null, so we can handle the null value as not assigned parameter), like you did in the url helper invoke.

...but i am sure i have probably missed something...

could be also be considered a generic helper and be used via the container in request handlers/middleware/controller-classes too and not a only a view helper?

kind regards,

maks

**Comment by dlundgren** [comment]
@pine3ree The $data value accepting a string is a typo in the documentation. I copied it from the example above it in the docs.

The goal is to make a generic helper that could be used as a view helper if desired.

@harikt The helper might be better off just returning results from generate or the Generator itself. This would allow to more easily add new methods, as well as a `raw` method, without requiring a major version bump, thoughts?

**Comment by harikt** [comment]
Hi @pine3ree ,

> I haven't looked in the aura repo for a while, but it took a look at your pr and surroundings (router v.3).
> so I apologize in advance if I will say something obviously wrong.

You don't need to apologize. It is very helpful that you are here to help us.

> The code looks fine to me with a couple of notes:

cool.

> I would drop support for string query params. some could add 'abc=123&def=345', others could add 'abc=123&amp;def=345', I think it's safer if the helper has the responsibility of escaping/or not the parameter separator. 

I believe there can be some scenarios people really need to use those features and it should not be limited. ie why kept the signature. I also understand in that case if they need they can skip passing the values and generate their own.

> The same reasoning could be applied to urlencode query params values. If you have a query string you would need to use parse_url, normalize (escape/unescape and/or encode/unencode) and regenerate a query string in line with your actual requirements.
> 
> I've looked at the code examples, but I don't understand the $data value be assigned a string while the signature expects an array

Yes that was a typo as @dlundgren mentioned. I also missed when updating the docs here.

> ...but i am sure i have probably missed something...

No there is nothing missing at your end.

> could be also be considered a generic helper and be used via the container in request handlers/middleware/controller-classes too and not a only a view helper?

Yes @jakejohns was asking the same https://github.com/auraphp/Aura.Router/pull/129#issuecomment-252431709

I want to think about the same.

Thanks once again for taking your time and providing valuable feedback.

**Comment by pmjones** [comment]
Hey @harikt -- as noted in #114, I think the extra query params and trailing fragment are out of scope here, as this is supposed to be a route helper, not a generic URL helper. I imagine it would be easy to combine it with a generic URL helper to add query string and fragment, and/or merely concatenate them onto the end of the generated string.

**Pull request closed without merging**
