### PR TITLE
Support serverIsSecure if code is behind the proxy

### PR DESCRIPTION
**Pull request by maskas**

### CODE REVIEW

**Comment by maskas** [comment]
Sorry. It looks like I've contributed the same change twice. 
Anyway. Are you going to accept this change?

**Comment by harikt** [comment]
Hi, 

I am ignorant so I have a question. Does adding something like this need to make sure the proxy is  trusted?

**Comment by maskas** [comment]
We are talking about node balancer or things like CloudFlare. I'm not sure, but I guess we have to know that it is trusted. I'm proposing this because I see others trusting this variable. Without it, you have to use HTTPS inside your network infrastructure behind the node balancer what is unnecessary to my oppinion. 

Do you think we need a hand controlled config to state if we want to trust this variable?

**Comment by harikt** [comment]
Hi @maskas , 

I don't know, I was just asking. You can wait for Paul M Jones reply.

**Comment by pmjones** [comment]
> I'm proposing this because I see others trusting this variable.

I am wary about trusting it, but I'm asking around. Can you give links to where other projects trust that value?

Thanks for your patience.

**Comment by maskas** [comment]
Here are some examples of people trusting this variable:

https://wordpress.org/support/topic/enable-http_x_forwarded_proto-for-reverse-proxyload-balancers
https://forge.typo3.org/issues/29693
http://stackoverflow.com/questions/452375/detecting-https-requests-in-php

Based on that header you can't be sure the connection is trusted. But behind the proxy it is the only way to know.

I'm not in a rush. If you see it valuable, use it. If not, you can leave it here for others to join to the discussion.

**Comment by pmjones** [comment]
Thanks for your patience.

Reading those links, they all (especially the typo3 one) seem very "iffy" about implementing it themselves, and point out that that it's not terribly secure. That, plus [this twitter exchange](https://twitter.com/pmjones/status/602870183317778432), make me think that relying on the header alone is a problem. It looks too easy to fake, and thus subvert the "secure" flag on the route.

Now, having said that, it might be that there's some more-secure way of checking the forwarded protocol. This series of methods in [Aura\Web\Request\Client](https://github.com/auraphp/Aura.Web/blob/2.x/src/Request/Client.php#L330-L398) may be useful in that regard. In particular, there needs to be a way to set a list of trusted proxies.

All that strikes me as a bit much for a routing system, but in your case it may actually be needed. As an alternative, perhaps you could check the incoming forwarded-for and forwarded-proto headers before the Router is invoked, and modify `$_SERVER['HTTPS']` accordingly? My guess is that would also be more performant, although by how much I can't say.

Further thoughts @maskas ?

p.s. Or instead of modifying `$_SERVER['HTTPS']` directly, modify only the `$server` input to the Router itself.

**Comment by maskas** [comment]
yes. Sounds like good points.

**Comment by pmjones** [comment]
With that, then, I'm going to close this PR, but we can reopen it later if needed. Let me know how things work out for you on this.

**Pull request closed without merging**
