### PR TITLE
Fix to resolve use for 5.3

### LINKED ISSUE #26: PHP version compatibility query
Hi,

Could I just check, other than PHP 5.4's new 'quick array' brackets ($array = [];) is there any other code in use that isn't php 5.3 compatible? I've been scouring through the source on github but cant see anything else other than the array brackets that would prevent php 5.3 compatibility.

### PR DESCRIPTION
**Pull request by harikt**
Closes #26

### CODE REVIEW

**Comment by harikt** [comment]
Travis passes , but there are a few changes made to make it compatible with 5.3

Please look into it before merging and let us see whether it is worth the time ;-) .

https://travis-ci.org/harikt/Aura.Router/jobs/8464928

**Comment by okaresz** [comment]
Thanks very much for this fix! It definitely saved me from a lot of trouble. :)

**Comment by harikt** [comment]
@okaresz you are welcome :+1:  .

**Comment by harikt** [comment]
Closing for we are not back porting to 5.3 . Current PHP version 5.5

**Pull request closed without merging**
