### PR TITLE
Using rawurlencode() instead of urlencode()

### PR DESCRIPTION
**Pull request by gpapadopg**
Sorry for the mesh with the commits :-/
At least, only the two files that i have changed is on the changelist now. If there are problems, please tell me to send another PR

### CODE REVIEW

**Comment by harikt** [comment]
I don't know how you can squash/squeesh? your commits.

This seems a lot of changes for composer also ?

**Comment by gpapadopg** [comment]
I made the mistake to commit the changes from my branch forked from an older branch of master (of Router). Should i drop it and try again?

**Comment by harikt** [comment]
If you are doing from master, no it should not be. It should come from
develop .

About your query to start again , I will say no . Let's wait for @pmjones
thoughts on this. Let him not merge. If he is ok , if its possible you can
start with a fresh one ?

By the way I looked how the google query is going. It seems + sign. I am
not sure which one is right or which is wrong really .

Thanks

**Comment by gpapadopg** [comment]
I guess google uses urlencode...

As for the commits, ok let @pmjones decide. Again, my apologies

**Comment by harikt** [comment]
> Again, my apologies
> 
> Don't apologies any more.  I will shoot you ;) . It happens :) .

Thank you for the hard work on it man!

**Pull request merged**
