### PR TITLE
Add test coverage

### PR DESCRIPTION
**Pull request by koriym**

### CODE REVIEW

**Comment by harikt** [comment]
If you are sending code-coverage to other repos feel free to merge it. No issues from my side.

**Comment by koriym** [comment]
The test failed in PHP 7.1.
https://github.com/auraphp/Aura.Router/runs/5047152396?check_suite_focus=true

Reason unknown yet. I'm trying fix it now.

**Comment by koriym** [comment]
@harikt Aura.Router, Aura.Session, Aura.Input and Aura.Intl were done.

**Comment by harikt** [comment]
Thank you.

**Pull request merged**
